### ISSUE TITLE
missing StageTiming.h

### ISSUE THREAD

**Issue by YoniChechik** [daniilidis-group/msckf_mono#21]
Currently receive an error in building the package due to a missing header file known as: "StageTiming.h"?

Is this due to missing a dependency? Or was the header file just not pushed, yet?

**Comment by k-chaney** [comment]
This is a message that needs to be built by ROS. The dependency list might not be working right inside of `CMakeLists.txt`. This is normally solved (without rewriting the `CMakeLists.txt`) by attempting to build multiple times in a row.

**Comment by nacorti** [comment]
I'm new at ROS, but I managed to make this error go away by adding 
`add_dependencies(asl_msckf msckf_mono_generate_messages_cpp)`

to the bottom of the CMakeLists.txt file in msckf_mono. This forces ROS to build the custom message header file (StageTiming.h) before it tries to compile the asl_msckf modules that depend on StageTiming

Interestingly, this builds successfully when I use `catkin_make`, but fails when I clean and try `catkin build`. Haven't gotten to the bottom of that yet.

Got that solution [here](http://answers.ros.org/question/306884/custom-message-fails-to-build-no-such-file-or-directory/)
