### ISSUE TITLE
test

### ISSUE THREAD

**Issue by jixiedaima** [daniilidis-group/msckf_mono#3]
Can the algorithm pass the Euroc datasets as a mono vio?

**Comment by jixiedaima** [comment]
Solved it.

**Comment by stihuangyuan** [comment]
@jixiedaima i have met an error when compile corner_detecor.cpp but with no description, how could you compile it succeed? I create a workspace and use catkin_make, thanks for your help.

**Comment by ycdfwzy** [comment]
> Solved it.

I tried to run this code on other Euroc datasets(except MH_03_medium.bag). I only modified the path to the bag in `msckf_mono/launch/euroc.launch`, but the system failed because of drifting. How did you solve this problem? @jeffdelmerico @k-chaney @jeffdelmerico @volcanoh
